import os
import sys
import json
import logging
from logging.handlers import RotatingFileHandler
from flask import Flask, render_template, request, jsonify
from flask_cors import CORS
from dotenv import load_dotenv
from google import genai
from google.genai import types
from pydantic import BaseModel, Field, field_validator, ValidationError
from flask_limiter import Limiter, RateLimitExceeded
from flask_limiter.util import get_remote_address
from werkzeug.exceptions import HTTPException

# Load environment variables
load_dotenv()

# Configure Logging (rotating file handler + console logging)
log_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "logs")
os.makedirs(log_dir, exist_ok=True)
log_file = os.path.join(log_dir, "app.log")

# Setup logging config
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger()

# Add rotating file handler
try:
    file_handler = RotatingFileHandler(log_file, maxBytes=1024*1024, backupCount=5)
    file_handler.setFormatter(logging.Formatter('%(asctime)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s'))
    file_handler.setLevel(logging.INFO)
    logger.addHandler(file_handler)
    logger.info("Rotating file handler added to logger.")
except Exception as e:
    logger.error(f"Could not initialize log file handler: {e}")

# Validate configuration on startup
api_key = os.getenv("GEMINI_API_KEY")
is_testing = os.getenv("TESTING", "false").lower() in ("true", "1", "yes")

if not is_testing:
    if not api_key or api_key.strip() == "" or api_key == "your_gemini_api_key_here":
        logger.critical("CONFIGURATION ERROR: GEMINI_API_KEY environment variable is missing or placeholder value is found. App exiting.")
        sys.exit(1)

app = Flask(__name__)

# Configurable CORS origins
allowed_origins = os.getenv("ALLOWED_ORIGINS", "http://localhost:5000,http://127.0.0.1:5000").split(",")
CORS(app, resources={r"/api/*": {"origins": allowed_origins}})
logger.info(f"CORS initialized. Allowed origins: {allowed_origins}")

# Rate limiting configuration (storage in memory)
limiter = Limiter(
    key_func=get_remote_address,
    app=app,
    default_limits=["200 per day", "50 per hour"],
    storage_uri="memory://"
)

def get_genai_client():
    """Initializes and returns the Google GenAI client using loaded keys."""
    k = os.getenv("GEMINI_API_KEY")
    if not k or k.strip() == "" or k == "your_gemini_api_key_here":
        raise ValueError("GEMINI_API_KEY is missing or invalid. Please check your environment configuration.")
    return genai.Client(api_key=k)

# Pydantic Model for Input Validation
class PlanRequest(BaseModel):
    goal: str = Field(..., min_length=5, max_length=1500, description="The high level goals of the sprint")
    timeframe: str = Field(..., min_length=2, max_length=100, description="Timeline for deliverables")
    hours_per_week: float = Field(..., gt=0.0, le=168.0, description="Available weekly workload budget")

    @field_validator('goal', 'timeframe')
    @classmethod
    def check_not_empty(cls, v):
        if not v.strip():
            raise ValueError("Field cannot be empty or only whitespace.")
        return v.strip()

# System Prompts for Dual-Agent Architecture
AGENT_1_DECONSTRUCTOR_PROMPT = """
You are 'The Deconstructor', an elite Agile project strategist and master planner.
Your job is to take a large, overwhelming goal along with the timeframe and available hours per week, and break it down into chronological milestone phases and core actionable components.

Inputs to analyze:
- Goal: {goal}
- Timeframe: {timeframe}
- Available Hours per Week: {hours_per_week}

Instructions:
1. Break down the high-level goal into key sequential phases.
2. Identify all critical technical and operational deliverables required.
3. Provide raw task breakdowns for each phase with estimated hours for each task.
4. Organize chronologically. Be thorough and detailed.

Do not worry about formatting as strict JSON yet—focus on complete structural deconstruction and realistic task breakdown.
"""

AGENT_2_PRAGMATIC_REVIEWER_PROMPT = """
You are 'The Pragmatic Reviewer', a world-class productivity coach and burnout prevention expert.
You will receive a raw project deconstruction generated by Agent 1.

Your mission:
1. Audit the deconstruction against the user's weekly budget of {hours_per_week} hours.
2. Inject essential buffer margins (15-20% extra time), contingency rest periods, and burnout prevention guardrails.
3. Assign tasks into actionable weekly sprints fitting within the user's {timeframe} limit.
4. Assess overall plan feasibility and generate a Feasibility Score (0-100) with strategic advice.

CRITICAL REQUIREMENT: You MUST output ONLY valid JSON matching this exact structure:
{{
  "project_title": "Descriptive short title for the plan",
  "summary": "Brief executive summary of the strategy",
  "total_duration_weeks": 8,
  "weekly_hours_budget": 10,
  "feasibility_score": 88,
  "feasibility_notes": "Key observations on workload realism and pacing strategies.",
  "sprints": [
    {{
      "week_number": 1,
      "sprint_title": "Phase title or focus area",
      "objective": "Main goal for this week",
      "tasks": [
        {{
          "task_name": "Specific actionable task",
          "estimated_hours": 3.5,
          "suggested_schedule": "e.g., Mon/Wed evenings (1.75h each)",
          "buffer_note": "Includes 30m buffer for unexpected bugs/delays"
        }}
      ],
      "milestone_checkpoint": "What completed outcome proves success this week?"
    }}
  ]
}}
"""

@app.after_request
def add_security_headers(response):
    """Adds standard security headers to prevent clickjacking, sniff attacks, and enforce CSP."""
    response.headers['X-Content-Type-Options'] = 'nosniff'
    response.headers['X-Frame-Options'] = 'DENY'
    response.headers['X-XSS-Protection'] = '1; mode=block'
    response.headers['Referrer-Policy'] = 'strict-origin-when-cross-origin'
    
    # Establish Content Security Policy (allow local styling + specific CDNs)
    csp_policy = (
        "default-src 'self'; "
        "script-src 'self' 'unsafe-inline' https://unpkg.com; "
        "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; "
        "font-src 'self' https://fonts.gstatic.com; "
        "connect-src 'self';"
    )
    response.headers['Content-Security-Policy'] = csp_policy
    return response

@app.route("/")
def index():
    """Serves the main application UI."""
    return render_template("index.html")

@app.route("/api/generate-plan", methods=["POST"])
@limiter.limit("5 per minute")
def generate_plan():
    """
    API Endpoint for sequential dual-agent sprint schedule generation.
    Validates inputs using Pydantic, calls Agent 1 (Deconstructor) and Agent 2 (Pragmatic Reviewer).
    """
    try:
        raw_data = request.get_json()
        if not raw_data:
            return jsonify({"error": "Invalid request body. Expected JSON."}), 400

        # Map frontend key names to Pydantic attributes if needed
        # In this workspace, Javascript maps inputs to 'goal', 'timeframe', and 'hours_per_week'
        req_data = PlanRequest(**raw_data)
        
        goal = req_data.goal
        timeframe = req_data.timeframe
        hours_per_week = req_data.hours_per_week

        client = get_genai_client()

        # Step 1: Agent 1 (The Deconstructor)
        logger.info(f"Executing Agent 1 (The Deconstructor) for goal: '{goal[:60]}...'")
        agent_1_prompt = AGENT_1_DECONSTRUCTOR_PROMPT.format(
            goal=goal,
            timeframe=timeframe,
            hours_per_week=hours_per_week
        )
        
        agent_1_response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=agent_1_prompt,
            config=types.GenerateContentConfig(
                temperature=0.7
            )
        )
        agent_1_output = agent_1_response.text

        if not agent_1_output:
            logger.error("Agent 1 returned empty output.")
            return jsonify({"error": "Agent 1 (The Deconstructor) failed to generate a project deconstruction."}), 502

        # Step 2: Agent 2 (The Pragmatic Reviewer)
        logger.info("Executing Agent 2 (The Pragmatic Reviewer)...")
        agent_2_prompt = AGENT_2_PRAGMATIC_REVIEWER_PROMPT.format(
            timeframe=timeframe,
            hours_per_week=hours_per_week
        ) + f"\n\nRaw Deconstruction from Agent 1:\n{agent_1_output}"

        agent_2_response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=agent_2_prompt,
            config=types.GenerateContentConfig(
                temperature=0.3,  # lower temperature for high JSON structure consistency
                response_mime_type="application/json"
            )
        )

        plan_json_str = agent_2_response.text
        try:
            parsed_plan = json.loads(plan_json_str)
        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse JSON output from Agent 2: {e}. Output was: {plan_json_str}")
            return jsonify({
                "error": "Failed to structure the final plan correctly."
            }), 502

        logger.info(f"Plan successfully generated: {parsed_plan.get('project_title')}")
        return jsonify({
            "success": True,
            "data": parsed_plan
        }), 200

    except ValidationError as ve:
        logger.warning(f"Validation failure for request: {ve.errors()}")
        return jsonify({"error": "Validation failed", "details": ve.errors()}), 400
    except ValueError as ve:
        logger.warning(f"ValueError during execution: {ve}")
        return jsonify({"error": str(ve)}), 400
    except Exception as e:
        logger.error(f"Unhandled error during plan generation: {e}", exc_info=True)
        return jsonify({"error": f"An internal server error occurred: {str(e)}"}), 500

# Error Handlers for Global Application Safety
@app.errorhandler(ValidationError)
def handle_pydantic_validation_error(e):
    logger.warning(f"Pydantic Validation failed: {e}")
    return jsonify({"error": "Invalid request fields", "details": e.errors()}), 400

@app.errorhandler(RateLimitExceeded)
def handle_rate_limit_exceeded(e):
    logger.warning(f"Rate limiting trigger hit by client: {e}")
    return jsonify({"error": "Too many requests. You are limited to 5 plan generations per minute."}), 429

@app.errorhandler(HTTPException)
def handle_http_exceptions(e):
    logger.warning(f"HTTP exception: {e}")
    return jsonify({"error": e.description}), e.code

@app.errorhandler(Exception)
def handle_all_unhandled_exceptions(e):
    logger.error(f"CRITICAL: Unhandled backend error: {e}", exc_info=True)
    return jsonify({"error": "An unexpected error occurred. Please contact service support."}), 500

if __name__ == "__main__":
    port = int(os.getenv("PORT", 5000))
    debug = os.getenv("FLASK_ENV") == "development"
    logger.info(f"Starting server on port {port} (debug={debug})...")
    app.run(host="0.0.0.0", port=port, debug=debug)
